[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "docs/.vuepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build && npx pnpm run docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
