name: Deploy Blog

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Node ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node }}
           cache: yarn

      - name: 🔖 Run Deploy Script 🔖
        uses: x-cmd/action@main
        with:
          git_user: Zhengqbbb
          git_email: 1074059947@qq.com
          ssh_key: '${{ secrets.ssh_key }}'
          code: xws deploy
  
    